bitbar: xbar
# connection: wifi
# wifi_host: meshtastic.local
# 
connection: serial
serial_port: /dev/cu.usbserial-0001
use_https: False
# 
# connection: bluetooth
# ble_node: YOUR_NODE
# 
# Save files
#
# log_dir defaults to $XDG_DATA_DIR or $HOME
# log_dir: /tmp
log_nodes_jsonl: meshtastic-menubar-nodes.jsonl
log_nodes_csv: meshtastic-menubar-nodes.csv
log_wifi_report: meshtastic-menubar-wifi-report.json
log_traceroute_log: meshtastic-menubar-traceroute.log
# misc
font_mono: Menlo-Regular
interval: 5
debug: False